### ISSUE TITLE
Book (Cerebellum) broken

### ISSUE THREAD

**Issue by snino64** [tthsqe12/asm#1]
with   USE_BOOK        = 1 (in x86/fish.asm)

x86/fish.asm [46]:
	entry Start
macro entry [2]:
	store address at ELF:e_entry
Processed: store Start at ELF:e_entry
Error: symbol 'Start' is undefined or out of scope.
x86/fish.asm [169] x86/Think.asm [484]:
	call Book_GetMove
macro call [1] macro parse_jump_operand [11] macro parse_operand [10] macro parse_operand_value [32]:
	ns.imm = +op
Processed: @dest.imm = +Book_GetMove
Error: symbol 'Book_GetMove' is undefined or out of scope.
x86/fish.asm [180] x86/Uci.asm [237]:
.....

**Comment by tthsqe12** [comment]
Oh no, you are not supposed to be trying this repo yet. Of course the book features don't assemble as there is no "Book.asm".

**Comment by snino64** [comment]
Ok. Thanks

**Comment by mausalimi** [comment]
great progress, this does compile now. 👍
