### ISSUE TITLE
sys_futex failed

### ISSUE THREAD

**Issue by Altorffer** [tthsqe12/asm#10]
I have been getting "sys_futex failed" when manually 'quit'-ing asmFish via UCI. Concurrently, it also no longer is starting when added as engine to scidvspc. Neither of these problems existed before.

Linux kernel: 4.7.0-0.1-liquorix-amd64
Architecture: x86_64
asmFish: asmFish_2016-08-14_popcnt (exact commit: https://github.com/tthsqe12/asm/commit/9a21d78f7706001d4d06d3f131cd233394b0c330 )

**Comment by tthsqe12** [comment]
could you try the futextest in the linux folder
https://github.com/tthsqe12/asm/blob/master/Linux/futextest
it will print more detailed info about the fail.
Could you also give me more info about what you were doing before issuing the 'quit' command?
Can you get search threads started? Does everything appear normal until the 'quit' command?

**Comment by Altorffer** [comment]
> Could you also give me more info about what you were doing before issuing the 'quit' command?

Actually, just running 'bench'. It no longer functioned in scidvspc, with scidvspc throwing up an ambiguous error message about asmFish not returning an error code. I then decided to simply try asmFish from the commandline interface, to see if it worked at all.

It is at that point I ran into the futex error; 'bench' ran fine, 'quit' popped the futex. Although not 100% of the time. Tried something else just now; just launching asmFish and immediately quitting; it does not show the futex error. However, any activity will throw it, as follows:

--------------------
asmFish_2016-08-15_popcnt
go infinite
info depth 1 multipv 1 time 2 nps 10000 score cp 83 nodes 20 tbhits 0 pv e2e4
<snip>
stinfo depth 19 multipv 1 time 3519 nps 1087013 score cp 26 lowerbound nodes 3825200 tbhits 0 pv e2e4
opinfo depth 19 multipv 1 time 3606 nps 1089612 score cp 33 lowerbound nodes 3929142 tbhits 0 pv e2e4

info depth 19 multipv 1 time 3768 nps 1091039 score cp 33 nodes 4111037 tbhits 0 pv e2e4
bestmove e2e4 ponder e7e5
quit
sys_futex failed
--------------------

After doing the same with your binary 'futextest', I am getting this:

sys_futex in _EventWait failed rax: 0xfffffffffffffff5

And yes, until 'quit', asmFish is behaving normally. At least from the commandline. Again, it simply refuses to function in a GUI for me where it did function normally before.

**Comment by tthsqe12** [comment]
Can you try the two other binaries
ShouldBeOk
ShouldFail_ThreadCreate

I will soon be able to program for linux on a linux box to avoid this kind of things.

**Comment by nabildanial** [comment]
Both "ShouldBeOk" and "ShouldFail_ThreadCreate" binaries fired up "sys_mmap failed rax: 0xffffffffffffffa1" error on "Bash on Ubuntu on Windows".

**Comment by tthsqe12** [comment]
alright nabildanial, this is
#define EOPNOTSUPP      95      /* Operation not supported on transport endpoint */
which is clearly not my fault. I have no idea what this error means, and it looks like the "Bash on Ubuntu on Windows" folks have some work to do.

**Comment by Altorffer** [comment]
ShouldFail_ThreadCreate:

- Fails on 'setoption name Threads value 4', segvaults.
- Runs 'bench' and 'go infinite' just fine when started from commandline.
- Does NOT show the futex error.

ShouldBeOk:

- Fails on 'setoption name Threads value 4', segvaults.
- Runs 'bench' and 'go infinite' just fine when started from commandline.
- Does NOT show the futex error.

So, they generate the same results.

**Comment by tthsqe12** [comment]
Ok. Can you try the new one ReallyShouldBeOk?
I fixed the problem with multiple threads. However, I am curious where the fail was coming from in your original first post. The error checking in futextest was too aggressive as some of the futex syscalls are supposed to fail. However, the original asmFish_2016-08-13 had only one unnecessary error check in thread join code, which is what must have been triggering in asmFish_2016-08-13.
This ReallyShouldBeOk removes the unnecessary error checks but does print
"sys_futex would have failed here. everything is ok."
when the error in thread join would have been triggered. Can you run ReallyShouldBeOk and try to see this message either when quitting or decreasing the number of search threads?

**Comment by Altorffer** [comment]
> Ok. Can you try the new one ReallyShouldBeOk?

It would be my pleasure.

> This ReallyShouldBeOk removes the unnecessary error checks but does print
"sys_futex would have failed here. everything is ok."

It does indeed. First run it did not, second run it did.

> Can you run ReallyShouldBeOk and try to see this message either when quitting or decreasing the number of search threads?

'bench' is fine, 'go infinite' (immediately after launching from commandline) is fine, 'setoption name Threads value 4' no longer segvaults and, as stated, 'quit' does throw up the 'everything is ok' message occassionally.

Furthermore, it now is functioning as expected in GUI again. Great work all around and good to hear you were able to pinpoint the issue so quickly and accurately.
