### ISSUE TITLE
Linux : error with more than 1 thread

### ISSUE THREAD

**Issue by KarpHaus** [tthsqe12/asm#11]
Starting with version of August 13, There is an error when I try to enable more than 1 thread.  All linux builds (base, popcnt, bmi2) are affected, your builds and my compiles.
Intel Core I 5 - 16 GB RAM - Xubuntu 14.04 X64
Command line :
./asmFish_2016-08-13_popcnt
asmFish_2016-08-13_popcnt
setoption name Threads value 2
info string node 0 cores 4 mask 0x000000000000000f
segmentation fault (core dumped)

**Comment by tthsqe12** [comment]
yes, I know. I am fixing this right now

**Comment by KarpHaus** [comment]
The file "shouldbeOK" still produces the same error. Idem If I compile.

**Comment by KarpHaus** [comment]
setoption name Threads value 4
info string node 0 cores 4 mask 0x000000000000000f
info string node 0 has threads 0 1 2 3
ReallyShouldBeOk works well.
