### ISSUE TITLE
do large pages work for you?

### ISSUE THREAD

**Issue by tthsqe12** [tthsqe12/asm#13]
I changed one thing since the lptest.exe and am wonder if large pages still work. See the readme for directon on this.

**Comment by apassion28** [comment]
Large pages no longer works for me... I can tell by simply loading the engine and seeing that both the commit size and working set are both the same numbers. This was not the case when large pages was working... also your setoption name Hash value 16 gives no display anymore... I'm not sure what you did... but lp is completely broken.
‎
When the 'commit size' uses the full amount of hash, and the 'working set' only a small fraction, then you are using Lage pages.‎

**Comment by Ipmanchess** [comment]
apassion28 ,i think you forget "isready"

Here the output works ,even on this laptop i have No LP 

pedantFishW_2016-08-25_popcnt
setoption name Threads value 4
setoption name LargePages value true
setoption name Hash value 256
isready
info string hash set to 256 MiB
info string node 0 cores 4 group 0 mask 0x000000000000000f
info string node 0 has threads 0 1 2 3
readyok

Will do same on my i7 5960x where LP is enabled..

Ipman.

**Comment by Ipmanchess** [comment]
i7 5960x @4.5Ghz 8cores (HT Off) with LargesPages:

pedantFishW_2016-08-25_bmi2
setoption name Threads value 8
setoption name LargePages value true
setoption name Hash value 256
isready
info string hash set to 256 MiB page size 2048 KiB
info string node 0 cores 8 group 0 mask 0x00000000000000ff
info string node 0 has threads 0 1 2 3 4 5 6 7
readyok

asmFishW_2016-08-25_bmi2
setoption name Threads value 8
setoption name LargePages value true
setoption name Hash value 256
isready
info string hash set to 256 MiB page size 2048 KiB
info string node 0 cores 8 group 0 mask 0x00000000000000ff
info string node 0 has threads 0 1 2 3 4 5 6 7
readyok

Ipman.

**Comment by apassion28** [comment]
What do you mean by isready? When I run the exe I see no output....

**Comment by apassion28** [comment]
The working set and commit size of usage is the exact same size.... the working set should be way smaller than the commit size...size. Unless I am missing something here... I am using winboard.

**Comment by apassion28** [comment]
Nevermind... it looks like it is working... haha... I did not notice the large page gui option.... and I saw no documentation that it had been implemented. :+1: thank you Ipman.

**Comment by tthsqe12** [comment]
apassion28, I cannot write too much info at startup because this breaks interaction with the shredder gui. It is now more reliant on the standards which require 'isready' after setting options.
