### ISSUE TITLE
Opteron physical 4 node detected as 8 node

### ISSUE THREAD

**Issue by CoffeeOne** [tthsqe12/asm#14]
C:\Program Files\stockfish_dev>asmFishW_2016-08-24_popcnt.exe
asmFishW_2016-08-25_popcnt
setoption name threads value 2
isready
info string node 0 cores 4 group 0 mask 0x00000000000000ff
info string node 1 cores 4 group 0 mask 0x000000000000ff00
info string node 2 cores 4 group 0 mask 0x0000000000ff0000
info string node 3 cores 4 group 0 mask 0x00000000ff000000
info string node 4 cores 4 group 0 mask 0x000000ff00000000
info string node 5 cores 4 group 0 mask 0x0000ff0000000000
info string node 6 cores 4 group 0 mask 0xff00000000000000
info string node 7 cores 4 group 0 mask 0x00ff000000000000
info string node 0 has threads 0 1
info string node 1 has threads
info string node 2 has threads
info string node 3 has threads
info string node 4 has threads
info string node 5 has threads
info string node 6 has threads
info string node 7 has threads
readyok

**Comment by CoffeeOne** [comment]
I was curious: I found this program: 
https://technet.microsoft.com/en-us/sysinternals/cc835722
it gives a lot of output, here is a part of it:
Logical Processor to Socket Map:
****************------------------------------------------------  Socket 0
----------------****************--------------------------------  Socket 1
--------------------------------****************----------------  Socket 2
------------------------------------------------****************  Socket 3

Logical Processor to NUMA Node Map:
********--------------------------------------------------------  NUMA Node 0
--------********------------------------------------------------  NUMA Node 1
----------------********----------------------------------------  NUMA Node 2
------------------------********--------------------------------  NUMA Node 3
--------------------------------********------------------------  NUMA Node 4
----------------------------------------********----------------  NUMA Node 5
--------------------------------------------------------********  NUMA Node 6
------------------------------------------------********--------  NUMA Node 7

Approximate Cross-NUMA Node Access Cost (relative to fastest):
     00  01  02  03  04  05  06  07
00: 2.0 1.5 1.8 2.8 2.8 2.8 2.1 2.6
01: 1.5 1.1 1.9 2.3 4.3 4.3 1.6 2.0
02: 2.9 2.8 1.0 1.5 4.7 2.2 2.2 2.1
03: 4.5 4.4 1.6 1.0 2.2 1.6 2.2 1.7
04: 2.0 2.8 4.8 4.7 1.0 1.5 2.5 3.5
05: 1.9 2.4 3.4 1.5 1.5 1.0 3.9 1.9
06: 2.6 1.5 4.4 4.3 1.9 2.3 1.2 1.9
07: 2.5 2.2 2.8 2.8 1.9 2.5 1.5 1.2

**Comment by Rechenschieber** [comment]
What kind of Opteron is this? Bulldozer Opterons and later have 2 NUMA nodes per physical CPU, so I guess the detection is correct.

**Comment by tthsqe12** [comment]
new version allows you to fuse nodes for the purpose of per-node memory allocation. Let me know if it behaves as expected.

**Comment by tthsqe12** [comment]
now that your machine is done with the numa test, why not run the latest asmfish and give it the option
setoption name nodeaffinity value 0.1 2.3 4.5 6.7

**Comment by CoffeeOne** [comment]
Hi,
      
      Thx for providing this option!
      I started testing:
      I am now on Windows and compare benches betweem 
      setoption name NodeAffinity value 0.1 2.3 4.5 6.7 and
      setoption name NodeAffinity value all
      
      for both: bench 1024 64 24
      the "all" gives about 52MN/s on average
      the "0.1 .... bundling" for 4 parents gives about 50MN/s in
      average
      
      Don't be confused by the high values, there are other CPUs in the
      machine than last time,
      most likely Linux will be now 70MN/s ++
      
      So I need to run some games with cute-cli to know if the 4 node
      variant is good .....
      
      If you want to see some more benchmarks, please tell me.
      
      best regards Peter
      
      Am 16.09.2016 um 15:55 schrieb tthsqe12:
    
    
      now that your machine is done with the numa test, why not run
        the latest asmfish and give it the option
        setoption name nodeaffinity value 0.1 2.3 4.5 6.7
      —
        You are receiving this because you modified the open/close
        state.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/tthsqe12/asm","title":"tthsqe12/asm","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/tthsqe12/asm"}},"updates":{"snippets":[{"icon":"PERSON","message":"@tthsqe12 in #14: now that your machine is done with the numa test, why not run the latest asmfish and give it the option\r\nsetoption name nodeaffinity value 0.1 2.3 4.5 6.7"}],"action":{"name":"View Issue","url":"https://github.com/tthsqe12/asm/issues/14#issuecomment-247606708"}}}

**Comment by CoffeeOne** [comment]
OK, I started a small tests over night with fast games:
===
cutechess-cli.exe -repeat -rounds 1000 -tournament gauntlet -pgnout results.pgn -resign movecount=3 score=400 -draw movenumber=34 movecount=8 score=20 -concurrency 1 -openings file=2moves_v1.pgn format=pgn order=random plies=16 -engine name=asm8 cmd=pedantFishW_2016-09-14_popcnt.exe option.NodeAffinity=all -engine name=asm4 cmd=pedantFishW_2016-09-14_popcnt.exe option.NodeAffinity='0.1 2.3 4.5 6.7' -each proto=uci tc=12+0.12 option.Threads=64 option.Hash=128
===
Result:
....
Score of asm8 vs asm4: 109 - 112 - 778  [0.498] 999
Started game 1000 of 1000 (asm4 vs asm8)
Finished game 1000 (asm4 vs asm8): 1/2-1/2 {Draw by adjudication}
Score of asm8 vs asm4: 109 - 112 - 779  [0.498] 1000
ELO difference: -1
Finished match
=> so unfortunately, performance is the same, no gain.

**Comment by CoffeeOne** [comment]
and sorry for the strange formatting, it should have been just ascii text
