### ISSUE TITLE
Stalemate Bug

### ISSUE THREAD

**Issue by Videodr0me** [tthsqe12/asm#19]
In the following game after whites last move h7, asmfish did not make a move - most likely because the final position would be stalemate (all 6 men syzygy tb installed). Normal SF has no problems :

[Event "Wertungspartie, 5 min"]
[Site "Maschinenraum"]
[Date "2016.09.10"]
[Round "?"]
[White "Brainfish 190816 64"]
[Black "asmFishW_2016-08-31_popcnt"]
[Result "1/2-1/2"]
[ECO "B91"]
[WhiteElo "2542"]
[BlackElo "2512"]
[Annotator "0.43;??"]
[PlyCount "159"]
[EventDate "2016.09.10"]
[TimeControl "300"]

{Brainfish 190816 64 POPCNT (11 cores): 30.2 plies; 20.097kN/s Intel(R) Xeon(R)
CPU           X5680  @ 3.33GHz 4127MHz, (12 CPUs), 2017.ctg, 4096 MB} 1. e4 {
B 0} c5 {0} 2. Nf3 {B 0} d6 {0} 3. d4 {B 0} Nf6 {0} 4. Nc3 {B 0} cxd4 {0} 5.
Nxd4 {B 0} a6 {0} 6. g3 {B 0} g6 {0} 7. Bg2 {0.01/0 2} Bg4 {0} 8. Nde2 {0.43/
23 5} Nc6 {0 (Bd7)} 9. h3 {0.50/27 10} Bd7 {0} 10. Be3 {0.45/26 8} Bg7 {0} 11.
O-O {0.50/26 6} Rb8 {31 (0-0)} 12. Nd5 {0.61/24 10} O-O {11} 13. b3 {0.63/27 6}
Ne8 {14 (b5)} 14. Rc1 {0.62/28 6} b5 {1} 15. Qd2 {0.60/22 1} e6 {3 (a5)} 16.
Ndf4 {0.58/26 11} Ne5 {19 (Qa5)} 17. Rfd1 {0.47/27 20} Bc6 {12} 18. Nd3 {0.47/
28 0} Nf6 {17} 19. f3 {0.40/29 0} Nxd3 {11} 20. cxd3 {0.39/28 0} Bb7 {7} 21. h4
{0.43/27 7} Qd7 {17 (Qe7)} 22. d4 {0.41/28 6} Rfc8 {0} 23. Rxc8+ {0.46/26 9}
Qxc8 {5} 24. g4 {0.39/28 17} Qd8 {13 (h5)} 25. Nf4 {0.39/30 21} Rc8 {0} 26. g5
{0.45/28 3} Nd7 {14} 27. h5 {0.44/31 6} a5 {0} 28. h6 {0.41/27 1} Bf8 {5} 29.
d5 {0.41/30 0} e5 {5} 30. Nd3 {0.41/32 0} b4 {4} 31. Nb2 {0.41/31 1} Be7 {8}
32. Rc1 {0.41/33 0} Rxc1+ {5} 33. Qxc1 {0.41/36 3} Nc5 {9} 34. Qd2 {0.41/33 0}
Ba6 {4 (Bc8)} 35. Bf1 {0.41/33 4} Bc8 {0} 36. Bb5 {0.41/33 4} Qb6 {4} 37. Qe2 {
0.41/32 0} Qd8 {5} 38. Qg2 {0.41/33 0} Qb6 {3} 39. Bf1 {0.41/34 1} Qc7 {2} 40.
Nc4 {0.41/32 0} Ba6 {4} 41. Qc2 {0.41/34 0} Bc8 {3 (Qd8)} 42. Kh1 {0.41/30 13}
Ba6 {2} 43. Kg2 {0.41/30 12} Qd8 {0} 44. Qc1 {0.41/33 4} Bxc4 {5 (Bc8)} 45.
Bxc4 {0.41/32 10} a4 {0} 46. bxa4 {0.41/30 8} Nxa4 {6} 47. Bd3 {0.41/33 0} Nc5
{5} 48. Be2 {0.41/30 0} Qa5 {4} 49. Bc4 {0.34/28 1} Kf8 {1 (Qc7)} 50. Kh3 {0.
34/26 5} Na4 {4 (Kg8)} 51. a3 {0.11/29 4} Bd8 {0} 52. axb4 {0.11/28 0} Qxb4 {1}
53. Bd2 {0.04/30 4} Qc5 {0} 54. Be2 {0.04/30 0} Qxc1 {2} 55. Bxc1 {0.01/33 0}
Bb6 {2} 56. Kg2 {0.00/35 0} Bd4 {2} 57. Bc4 {0.00/35 2} Nb2 {2} 58. Bb5 {0.00/
37 0} Nd1 {1} 59. f4 {0.00/37 0} Nc3 {1} 60. Bd3 {0.00/39 1} exf4 {1} 61. Bxf4
{0.00/41 0} Ke7 {2} 62. Bc2 {0.00/41 0} Ne2 {3} 63. Bd2 {0.00/46 0} Bc3 {2} 64.
Bxc3 {0.00/48 1} Nxc3 {1} 65. Kf3 {0.00/39 0} f6 {1} 66. e5 {0.00/41 1} dxe5 {1
} 67. Bxg6 {0.00/41 0} e4+ {1} 68. Bxe4 {0.00/43 1} Nxe4 {0} 69. Kxe4 {0.00/81
0} fxg5 {0} 70. Kf5 {0.00/42 2} Kd6 {1} 71. Kxg5 {0.00/47 11} Ke5 {0} 72. d6 {0
} Kxd6 {1} 73. Kf6 {0} Kd5 {2} 74. Kg7 {0} Ke6 {0} 75. Kg8 {0} Kf6 {2} 76. Kxh7
{0} Kf7 {0} 77. Kh8 {0.00/1 0} Kf8 {0} 78. Kh7 {0} Kf7 {0} 79. Kh8 {0.00/1 0}
Kg6 {0} 80. h7 (asmFishW_2016-08-31_popcnt POPCNT
delivered no move.} 1-0

**Comment by tthsqe12** [comment]
confirmed and fixed - Thanks!

**Comment by Videodr0me** [comment]
Great, but I can’t seem to find the fix on github?!

 

Von: tthsqe12 [mailto:notifications@github.com] 
Gesendet: Dienstag, 13. September 2016 04:44
An: tthsqe12/asm
Cc: Videodr0me; Author
Betreff: Re: [tthsqe12/asm] Stalemate Bug (#19)

 

confirmed and fixed - Thanks!
