### ISSUE TITLE
Best move ordering bug is back.

### ISSUE THREAD

**Issue by hero2017** [tthsqe12/asm#21]
I just compiled the latest asmFish (2016-09-16) and I'm seeing 'no info' for the top moves in Aquarium. I compiled pedantFishW 2016-09-16 and this one is fine.

**Comment by tthsqe12** [comment]
new version has this in all versions. You can modify the settings in Def.asm
https://github.com/tthsqe12/asm/search?utf8=%E2%9C%93&q=CURRMOVE_MIN_DEPTH&type=Code

**Comment by hero2017** [comment]
This would not resolve the issue since I'm seeing this even after depth 20 (any depth) and after 3000 (50 seconds?).

The "workaround" that worked for me was to comment out the following lines in searchmacros.asm:

1736, 1773, 818 and 829
