### ISSUE TITLE
New version has lower performance

### ISSUE THREAD

**Issue by Rechenschieber** [tthsqe12/asm#23]
I tried the new version and I'm getting roughly 5% less kn/s in the starting position compared to the version from August 25. The computer is a 2x Xeon E5-2696v4 - 44 cores, 88 threads, 2 processor groups, Windows 7, large pages working fine, 64 GB RAM, 4GB hash. (Size of hash doesn't matter).

Btw. thank you for your great work - performance is really stunning  and it's great to get large pages and processor groups are handled correctly.   :)

**Comment by Rechenschieber** [comment]
Update: the same does apply to a smaller computer: 2x Xeon E5-2696v2 - 24 cores, 48 threads, only one processor group, Windows 7, large pages. I tried switching off NUMA in the BIOS - this had no effect.

**Comment by tthsqe12** [comment]
asmfish follows the functionality of official stockfish. Updates to pruning and evaluation can change the nps figure.

**Comment by Rechenschieber** [comment]
Tank you very much
