### ISSUE TITLE
Command inconsistency with go movetime 

### ISSUE THREAD

**Issue by nssy** [tthsqe12/asm#27]
# Sometimes asmFish goes on an infinite analysis even when I specify the movetime

Here is an example on linux
**./asmFish
setoption name Threads value 4
setoption name Hash value 1024
position fen 4rrk1/1bpR1p2/1pq1pQp1/p3P2p/P1PR3P/5N2/2P2PP1/6K1 w - - 0 31
go movetime 160000**

The engine will continue to search even after the specified 160 seconds are over.
Other times like 60 seconds, 120 seconds seam to work ok

**Comment by tthsqe12** [comment]
confirmed, im looking into it

**Comment by tthsqe12** [comment]
Let me know if latest version fixed this for you. This bug should have affected older versions when the movetime was a multiple of 256ms.

**Comment by nssy** [comment]
Works like a charm now. Much appreciated Mohammed.
