### ISSUE TITLE
asmFish will not load.... even exe crashes...

### ISSUE THREAD

**Issue by apassion28** [tthsqe12/asm#28]
Mohammed here is what i found in the event log...

Faulting application name: asmFishW_--1--1_bmi2.exe, version: 0.0.0.0, time stamp: 0x5804ec1c
Faulting module name: asmFishW_--1--1_bmi2.exe, version: 0.0.0.0, time stamp: 0x5804ec1c
Exception code: 0xc0000005
Fault offset: 0x00000000001507b9
Faulting process id: 0xf8c
Faulting application start time: 0x01d2288bb5999d4a
Faulting application path: C:\WinBoard-4.8.0\asm-master\Windows\asmFishW_--1--1_bmi2.exe
Faulting module path: C:\WinBoard-4.8.0\asm-master\Windows\asmFishW_--1--1_bmi2.exe
Report Id: d6db1bd5-fc25-4e95-8baa-d9e02062e4b2
Faulting package full name: 
Faulting package-relative application ID: 

 Name]  Application Error 
 
  - EventID 1000 

   [ Qualifiers]  0 
 
   Level 2 
 
   Task 100 
 
   Keywords 0x80000000000000 
 
  - TimeCreated 

   [ SystemTime]  2016-10-17T15:32:46.050277200Z 
 
   EventRecordID 8715 
 
   Channel Application 
 
   Computer Polyphemus 
 
   Security 
 

- EventData 

   asmFishW_--1--1_bmi2.exe 
   0.0.0.0 
   5804ec1c 
   asmFishW_--1--1_bmi2.exe 
   0.0.0.0 
   5804ec1c 
   c0000005 
   00000000001507b9 
   f8c 
   01d2288bb5999d4a 
   C:\WinBoard-4.8.0\asm-master\Windows\asmFishW_--1--1_bmi2.exe 
   C:\WinBoard-4.8.0\asm-master\Windows\asmFishW_--1--1_bmi2.exe 
   d6db1bd5-fc25-4e95-8baa-d9e02062e4b2

**Comment by tthsqe12** [comment]
confirmed - looking into it

**Comment by tthsqe12** [comment]
I don't know what is going on.
Please try the debug_bmi2.exe in the windows folder and report the output/behavior

**Comment by apassion28** [comment]
Mohammed, I ran the debug utility. Once again, the thing crashed every single time. However, I have a picture of everything that the executable had reported. Is it something NUMA related or something to do with accessing of the memory? Again, every single version, including 10-14-2016, prior works flawlessly.


APassion,

________________________________

**Comment by apassion28** [comment]
![debugreport](https://cloud.githubusercontent.com/assets/21234551/19450893/394c813a-9479-11e6-8e3d-72491f596417.png)

**Comment by tthsqe12** [comment]
I know what is going on now in your case with 2 nodes. Should be fixed soon

**Comment by apassion28** [comment]
Thank you. :+1: )

**Comment by apassion28** [comment]
Work perfectly Mohammed! Thank you!
