### ISSUE TITLE
NumaTest_base.exe output

### ISSUE THREAD

**Issue by nabildanial** [tthsqe12/asm#3]
This is not an issue. I just want to leave it here for information, hope it'll benefit you or others. This is an output from my single-CPU 18 cores Xeon v3, Windows 10. You can close this issue after reading.

 *** General Verbosity ON !! ***

*** enumerating nodes ***
node number = 0: group = 0, mask = 0x0000000FFFFFFFFF
*** finished enumerating nodes ***

*** enumerating processor cores ***
 group = 0, mask = 0x0000000000000003, belongs to node 0
 group = 0, mask = 0x000000000000000C, belongs to node 0
 group = 0, mask = 0x0000000000000030, belongs to node 0
 group = 0, mask = 0x00000000000000C0, belongs to node 0
 group = 0, mask = 0x0000000000000300, belongs to node 0
 group = 0, mask = 0x0000000000000C00, belongs to node 0
 group = 0, mask = 0x0000000000003000, belongs to node 0
 group = 0, mask = 0x000000000000C000, belongs to node 0
 group = 0, mask = 0x0000000000030000, belongs to node 0
 group = 0, mask = 0x00000000000C0000, belongs to node 0
 group = 0, mask = 0x0000000000300000, belongs to node 0
 group = 0, mask = 0x0000000000C00000, belongs to node 0
 group = 0, mask = 0x0000000003000000, belongs to node 0
 group = 0, mask = 0x000000000C000000, belongs to node 0
 group = 0, mask = 0x0000000030000000, belongs to node 0
 group = 0, mask = 0x00000000C0000000, belongs to node 0
 group = 0, mask = 0x0000000300000000, belongs to node 0
 group = 0, mask = 0x0000000C00000000, belongs to node 0
*** finished enumerating processor cores ***

*** matching cores to nodes ***
node number = 0: group = 0, mask = 0x0000000FFFFFFFFF, cores in node = 18, cmh table = 0x0000000001AA0000
 total processor cores found: 18
*** finished matching cores to nodes ***

Thread_IdleLoop enter
response time:  75811 us
response time:  83118 us
setoption name threads value 18
Thread_IdleLoop enter
Thread_IdleLoop enter
Thread_IdleLoop enter
Thread_IdleLoop enter
Thread_IdleLoop enter
Thread_IdleLoop enter
Thread_IdleLoop enter
Thread_IdleLoop enter
Thread_IdleLoop enter
Thread_IdleLoop enter
Thread_IdleLoop enter
Thread_IdleLoop enter
Thread_IdleLoop enter
Thread_IdleLoop enter
Thread_IdleLoop enter
Thread_IdleLoop enter
Thread_IdleLoop enter
response time:  10272 us
response time:  0 us
go depth 25
response time:  178 us
MainThread_Think
response time:  0 us
Thread_Think
Thread_Think
Thread_Think
Thread_Think
Thread_Think
Thread_Think
Thread_Think
Thread_Think
Thread_Think
Thread_Think
Thread_Think
Thread_Think
Thread_Think
Thread_Think
Thread_Think
Thread_Think
Thread_Think
Thread_Think
info depth 1 multipv 1 time 10 nps 4506700 score cp 22 nodes 45067 tbhits 0 pv d2d4
info depth 2 multipv 1 time 17 nps 9910529 score cp 33 nodes 168479 tbhits 0 pv d2d4 g8f6
info depth 3 multipv 1 time 18 nps 10181166 score cp 39 nodes 183261 tbhits 0 pv e2e4 d7d5 e4d5 d8d5
info depth 4 multipv 1 time 18 nps 10875000 score cp 36 nodes 195750 tbhits 0 pv e2e4 e7e5 d2d4 e5d4
info depth 5 multipv 1 time 19 nps 11020526 score cp 29 nodes 209390 tbhits 0 pv e2e4 e7e5 g1f3 g8f6 d2d4
info depth 6 multipv 1 time 20 nps 11361500 score cp 27 nodes 227230 tbhits 0 pv d2d4 g8f6 b1c3 d7d5 c1f4 e7e6
info depth 7 multipv 1 time 21 nps 12159428 score cp 26 nodes 255348 tbhits 0 pv g1f3 d7d5 d2d4 e7e6 e2e3 c7c5 b1c3 c5d4 f1b5 c8d7 e3d4
info depth 8 multipv 1 time 22 nps 12301227 score cp 29 nodes 270627 tbhits 0 pv g1f3 d7d5 d2d4 e7e6 e2e3 c7c5 b1c3 c5d4 f1b5 c8d7
info depth 9 multipv 1 time 23 nps 12810434 score cp 21 upperbound nodes 294640 tbhits 0 pv g1f3 d7d5
info depth 9 multipv 1 time 25 nps 13600240 score cp 27 nodes 340006 tbhits 0 pv g1f3 d7d5 d2d4 c7c5 e2e3 e7e6 f1e2 b8c6 e1g1 c8d7
info depth 10 multipv 1 time 27 nps 14478370 score cp 20 upperbound nodes 390916 tbhits 0 pv g1f3 d7d5
info depth 10 multipv 1 time 28 nps 14883785 score cp 32 lowerbound nodes 416746 tbhits 0 pv e2e4
info depth 10 multipv 1 time 29 nps 15038620 score cp 31 nodes 436120 tbhits 0 pv e2e4 e7e5 d2d4 e5d4 d1d4 b8c6 d4c4 f7f5 b1c3 g8f6
info depth 11 multipv 1 time 30 nps 15528533 score cp 38 lowerbound nodes 465856 tbhits 0 pv e2e4
info depth 11 multipv 1 time 31 nps 15780032 score cp 44 nodes 489181 tbhits 0 pv e2e4 e7e5 b1c3 b8c6 g1f3 g8f6 d2d4 e5d4 f3d4 f8b4 d4c6 b4c3 b2c3
info depth 12 multipv 1 time 33 nps 15975272 score cp 43 nodes 527184 tbhits 0 pv e2e4 e7e5 g1f3 g8f6 d2d4 e5d4 e4e5 f6e4 d1e2 e4c5 f3d4 b8c6 d4b5
info depth 13 multipv 1 time 38 nps 16893657 score cp 36 upperbound nodes 641959 tbhits 0 pv e2e4 e7e5
info depth 13 multipv 1 time 43 nps 17661302 score cp 29 upperbound nodes 759436 tbhits 0 pv e2e4 e7e5
info depth 13 multipv 1 time 62 nps 19292000 score cp 32 nodes 1196104 tbhits 0 pv e2e4 e7e5 g1f3 b8c6 f1c4 g8f6 b1c3 f8c5 d2d3 d7d6 c1g5 e8g8 e1g1 c6d4 c3d5
info depth 14 multipv 1 time 64 nps 19517609 score cp 25 upperbound nodes 1249127 tbhits 0 pv e2e4 e7e5
info depth 14 multipv 1 time 76 nps 20310144 score cp 19 nodes 1543571 tbhits 0 pv e2e4 e7e5 b1c3 g8f6 f1c4 f8b4 g1f3 d7d6 e1g1 e8g8 d2d3 c7c6 c1g5 h7h6 g5f6 d8f6
info depth 15 multipv 1 time 110 nps 21310345 score cp 18 nodes 2344138 tbhits 0 pv e2e4 e7e5 b1c3 g8f6 f1c4 f8b4 g1f3 b8c6 c3d5 f6e4 d1e2 f7f5 e1g1 b4d6 d2d3 e4f6 c1g5
info depth 16 multipv 1 time 200 nps 22377895 score cp 18 nodes 4475579 tbhits 0 pv e2e4 e7e5 b1c3 g8f6 g1f3 f8b4 f3e5 e8g8 e5d3 b4c3 d2c3 f6e4 f1e2 b8c6 e1g1 d7d5 c1f4 f8e8 f1e1 c8d7
info depth 17 multipv 1 time 285 nps 22912877 score cp 25 lowerbound nodes 6530170 tbhits 0 pv e2e4
info depth 17 multipv 1 time 305 nps 23012934 score cp 32 lowerbound nodes 7018945 tbhits 0 pv e2e4
info depth 17 multipv 1 time 406 nps 23184785 score cp 25 upperbound nodes 9413023 tbhits 0 pv e2e4 e7e5
info depth 17 multipv 1 time 496 nps 23221512 score cp 23 nodes 11517870 tbhits 0 pv e2e4 e7e5 g1f3 b8c6 f1b5 a7a6 b5c6 d7c6 e1g1 g8f6 f3e5 f6e4 e5f3 f8e7 d1e2 e4f6 f1e1 c8e6 f3g5
info depth 18 multipv 1 time 602 nps 23265573 score cp 24 nodes 14005875 tbhits 0 pv e2e4 e7e6 d2d4 d7d5 e4d5 e6d5 f1d3 g8f6 g1f3 f8e7 e1g1 e8g8 c1f4 b8c6 c2c3 f6e4 f1e1 c8f5 d3e4 f5e4
info depth 19 multipv 1 time 740 nps 23493883 score cp 23 nodes 17385474 tbhits 0 pv e2e4 e7e6 d2d4 d7d5 e4d5 e6d5 g1f3 g8f6 f1d3 f8d6 e1g1 e8g8 b1c3 c7c6 f1e1 h7h6 d1d2 c8g4 f3e5 d6e5 d4e5
info depth 20 multipv 1 time 1024 nps 23645813 score cp 16 upperbound nodes 24213313 tbhits 0 pv e2e4 e7e6
info depth 20 multipv 1 time 1460 nps 23782506 score cp 20 nodes 34722459 tbhits 0 pv e2e4 e7e6 d2d4 d7d5 e4d5 e6d5 f1d3 f8d6 g1f3 g8f6 e1g1 e8g8 b1c3 b8c6 c3b5 c6b4 b5d6 d8d6 f3e5 b4d3 d1d3 c8e6 f2f3 f6d7 c1f4 d6b6
info depth 21 multipv 1 time 3769 nps 23730963 score cp 13 nodes 89442002 tbhits 0 pv e2e4 e7e6 d2d4 d7d5 e4d5 e6d5 b1c3 g8f6 g1f3 f8d6 f1d3 e8g8 e1g1 c7c6 h2h3 f8e8 f1e1 c8e6 f3e5 b8d7 c1f4 d7e5 d4e5
info depth 22 multipv 1 time 5319 nps 23642197 score cp 20 lowerbound nodes 125752846 tbhits 0 pv e2e4
info depth 22 multipv 1 time 5555 nps 23632398 score cp 13 upperbound nodes 131277972 tbhits 0 pv e2e4 e7e6
info depth 22 multipv 1 time 5897 nps 23625392 score cp 20 lowerbound nodes 139318938 tbhits 0 pv e2e4
info depth 22 multipv 1 time 6270 nps 23618236 score cp 19 nodes 148086341 tbhits 0 pv e2e4 e7e6 d2d4 d7d5 b1d2 g8f6 e4e5 f6d7 c2c3 c7c5 f1d3 b8c6 g1e2 c5c4 d3c2 f8e7 e1g1 b7b5 e2f4 g7g6 a2a4 b5b4 g1h1
info depth 23 multipv 1 time 7846 nps 23575269 score cp 26 lowerbound nodes 184971565 tbhits 0 pv e2e4
info depth 23 multipv 1 time 8024 nps 23575521 score cp 19 upperbound nodes 189169983 tbhits 0 pv e2e4 e7e6
info depth 23 multipv 1 time 8330 nps 23575500 score cp 26 lowerbound nodes 196383916 tbhits 0 pv e2e4
info depth 23 multipv 1 time 9020 nps 23561039 score cp 17 upperbound nodes 212520576 tbhits 0 pv e2e4 e7e6
info depth 23 multipv 1 time 9716 nps 23544480 score cp 26 nodes 228758172 tbhits 0 pv e2e4 e7e6 d2d4 d7d5 b1d2 c7c5 g1f3 g8f6 e4d5 e6d5 f1b5 c8d7 b5d7 b8d7 e1g1 f8e7 d4c5 d7c5 d2b3 c5e4 f3d4 e8g8 c1e3 e7d6 d4f5 d6c7 b3d4 e4d6 f1e1 d6f5 d4f5 f8e8
info depth 24 multipv 1 time 11067 nps 23520830 score cp 19 upperbound nodes 260305032 tbhits 0 pv e2e4 e7e6
info depth 24 multipv 1 time 12286 nps 23505591 score cp 22 nodes 288789698 tbhits 0 pv e2e4 e7e6 d2d4 d7d5 b1d2 c7c5 e4d5 d8d5 g1f3 c5d4 f1c4 d5d6 e1g1 g8f6 d2b3 b8c6 b3d4 c6d4 d1d4 d6d4 f3d4 c8d7 c1f4 a8c8 c4d3 f8c5 d4b3 c5b6 f4d6 d7c6 a1d1 f6e4 d6a3
info depth 25 multipv 1 time 12921 nps 23514187 score cp 21 nodes 303826812 tbhits 0 pv e2e4 e7e6 d2d4 d7d5 b1d2 c7c5 g1f3 g8f6 e4d5 e6d5 f1b5 c8d7 b5d7 b8d7 e1g1 f8e7 d4c5 d7c5 d2b3 c5e4 f3d4 e8g8 c2c3 f8e8 c1e3 e4d6 b3c5 d6c4 c5d3 a8c8 e3g5 e7d6
Thread_Think returning
Thread_Think returning
Thread_Think returning
Thread_Think returning
Thread_Think returning
Thread_Think returning
Thread_Think returning
Thread_Think returning
Thread_Think returning
Thread_Think returning
Thread_Think returning
Thread_Think returning
Thread_Think returning
Thread_Think returning
Thread_Think returning
Thread_Think returning
Thread_Think returning
Thread_Think returning
bestmove e2e4 ponder e7e6
MainThread_Think returning

**Comment by tthsqe12** [comment]
thank you!
