### ISSUE TITLE
Cerebellum licensing

### ISSUE THREAD

**Issue by tzipproth** [tthsqe12/asm#31]
Hi, I'm the Cerebellum / Brainfish developer.

I just saw that you created a tool to convert the Cerebellum library into a Polyglot book. That ist perfectly ok.

But due to the licensing of Cerebellum as Creative Commom Share Alike, every distribution of a copy or conversion of the original Cerebellum_light.bin into another format must contain the original licensing file distributed with Cerebellum_light.bin. That license is for data similar to what the GPL is for source code. A download of the Polyglot book only like I saw in Depth36BrainPolyglot.zip is not legal.

https://github.com/tthsqe12/asm/blob/master/BrainBook/
https://github.com/tthsqe12/asm/blob/master/BrainBook/Depth36BrainPolyglot.zip

Just wanted to mention this, because there will be a commercial Version of Cerebellum in the future. It's no problem for me that there was a mistake, we are all engine chess fans and mainly concentrating on developing new things :)

Thomas

a.	Attribution.
1.	If You Share the Licensed Material (including in modified form), You must:
A.	retain the following if it is supplied by the Licensor with the Licensed Material:
i.	identification of the creator(s) of the Licensed Material and any others designated to receive attribution, in any reasonable manner requested by the Licensor (including by pseudonym if designated);
ii.	a copyright notice;
iii.	a notice that refers to this Public License;
iv.	a notice that refers to the disclaimer of warranties;
v.	a URI or hyperlink to the Licensed Material to the extent reasonably practicable;

**Comment by tthsqe12** [comment]
Is the new Cerebellum folder acceptable?

**Comment by tzipproth** [comment]
Yes, if the Licencse file is included (similar to GPL), everything is ok.

Thanks,
Thomas
