### ISSUE TITLE
Big sized .bin opening books not working

### ISSUE THREAD

**Issue by massimilianogoi** [tthsqe12/asm#5]
asmFish doesn't read at all Polyglot (.bin) books sized more than 250 MB, while any other engines do. Sometimes it happens also even with 170-180 MB books

**Comment by tthsqe12** [comment]
A limit of 256MiB is coded into the engine. As long as the file size is < 256MiB, a multiple of 16, and at least 16, then it should load. With your 170-180MB books, what is the error message from the eninge (if there is one)?

**Comment by massimilianogoi** [comment]
It simply don't use the book. the actual size is 178MB but it still doesn't work... Couldn't you override that 256 MB limit? It should be useful having Polyglot opening books even sized gigabytes for the machines tournaments. I've tested in matches every possible engine and asmFish is the strongest, it has only this lack compared to the others.

**Comment by tthsqe12** [comment]
It should work with 178MB book. Could you somehow get this book to me (or another smaller book that is similarly not working)?

**Comment by massimilianogoi** [comment]
Yes, I've tried to find you in any way but I couldn't reach you. The book is private, I need a safe way to send it. You can write me an email at http://chess.massimilianogoi.com/contacts.php

**Comment by tthsqe12** [comment]
I downloaded it but it doesn't extract. The archive is 69.7MB

**Comment by massimilianogoi** [comment]
Substituted the file, please try now.

**Comment by tthsqe12** [comment]
Ok, got it.

**Comment by tthsqe12** [comment]
seems to work for me. Can you give me specific positions where you are having trouble? This might be a windows specific issue, in which case it will be a little longer to sort out the issue.

```
$ ./asmfish
asmFishL_2017-11-06_popcnt
setoption name bookfile value prototype.bin
info string 7631848 entries in book (0 entries have zero weight)
bookprobe 3
e2e4(255) e7e5(255) g1f3(255) 
          c7c5(127) g1f3(255) 
d2d4(127) d7d5(255) c2c4(255) 
          g8f6(127) c2c4(255) 
setoption name ownbook value true
go wtime 1000
info string playing book move weight 255
bestmove e2e4 ponder e7e5
position startpos moves e2e4
go btime 1000
info string playing book move weight 255
bestmove e7e5 ponder g1f3
position startpos moves e2e4 e7e5
go wtime 1000
info string playing book move weight 255
bestmove g1f3 ponder b8c6
position startpos                     
go wtime 1000 
info string playing book move weight 127
bestmove d2d4 ponder d7d5
go wtime 1000
info string playing book move weight 255
bestmove e2e4 ponder e7e5
go wtime 1000
info string playing book move weight 255
bestmove e2e4 ponder e7e5
setoption name bestbook move value true
error: unknown option bestbook
setoption name bestbookmove value true
go
info string playing book move weight 255
bestmove e2e4 ponder e7e5
go
info string playing book move weight 255
bestmove e2e4 ponder e7e5
go
info string playing book move weight 255
bestmove e2e4 ponder e7e5
go
info string playing book move weight 255
bestmove e2e4 ponder e7e5
book probe 5
error: unknown command book
bookprobe 5
e2e4(255) e7e5(255) g1f3(255) b8c6(255) f1b5(127) 
                                        f1c4(255) 
          c7c5(127) g1f3(255) d7d6(255) d2d4(255) 
                              b8c6(127) b1c3(127) 
                                        d2d4(255) 
d2d4(127) d7d5(255) c2c4(255) e7e6(255) g1f3(127) 
                                        b1c3(255) 
          g8f6(127) c2c4(255) e7e6(255) g2g3(255) 
                                        g1f3(127) 
quit
$

**Comment by massimilianogoi** [comment]
Starting position, interface used: Playchess, Fritz 15 (Chessbase).

**Comment by mausalimi** [comment]
as far as i can tell the book is used in arena

**Comment by massimilianogoi** [comment]
No, the UCI interfaces are universal. asmFish uses the .bin books through its own interface, thus undepending on what GUI you are using, whether it's Chessbase, Fritz or Arena.

**Comment by mausalimi** [comment]
and how about this (shortened) log output?
>setoption name OwnBook value true
setoption name BookFile value C:\Program Files\Arena Chess\Engines\asmFishW\prototype.bin
info string 7631848 entries in book (0 entries have zero weight)
isready
info string hash set to 128 MB no large pages
info string node 0 has threads 0 1 2
readyok
ucinewgame
isready
readyok
position startpos moves e2e4
go wtime 300000 btime 300000 winc 0 binc 0
info string playing book move weight 255
bestmove e7e5 ponder g1f3
position startpos moves e2e4 e7e5 g1f3
go ponder wtime 300000 btime 300000 winc 0 binc 0
info string playing book move weight 255
bestmove b8c6 ponder f1c4
position startpos moves e2e4 e7e5 b1c3
go wtime 296739 btime 300000 winc 0 binc 0
info string playing book move weight 255
bestmove g8f6 ponder d2d4
position startpos moves e2e4 e7e5 b1c3 g8f6 d2d4
go ponder wtime 296739 btime 299943 winc 0 binc 0
quit
info depth 18 seldepth 30 multipv 1 time 4185 nps 861235 score cp 21 nodes 3604272 hashfull 201 tbhits 0 pv e5d4
info string playing book move weight 255
bestmove e5d4 ponder d1d4

to be honest, i don't know anything about it. :)

**Comment by massimilianogoi** [comment]
Ok, made a bunch of tests by my self: this is an occasional bug, it happens too few times to be considered relevant. I left open this issue asking if it's possible to raise the 256 MB size limit (which question was part of the first post).
